### ISSUE TITLE
Entanglement doesn't support children array

### ISSUE THREAD

**Issue by pirelenito** [react-entanglement/react-entanglement#5]

**Comment by xaviervia** [comment]
Do you have a plan on how to fix?

**Comment by pirelenito** [comment]
It is very simple. We just need to wrap the children on a parent element (such as a `<span>`).

**Comment by pirelenito** [comment]
Because there can be only one value returned.

**Comment by xaviervia** [comment]
With the new `Scatter`/`Materialize` API, support for children might no longer make sense. Should we close this one?

**Comment by pirelenito** [comment]
No longer valid.
