### ISSUE TITLE
Memoize scatter

### ISSUE THREAD

**Issue by xaviervia** [react-entanglement/react-entanglement#7]
Assuming the API supports passing a `communicationAdapter` directly as a prop of the scattered version ( #6 ), it would be nice to be able retrieve the scattered version in a stateless component, like:

``` javascript
function ScatteredButton ({ label, communicationAdapter }) {
  const Scattered = scatter(Button, communicationAdapter)
  return <Scattered />
}
```

In the current implementation this could lead to get a new class each time, which might create problems for React, but if `scatter` were to be memoized that risk would be eliminated.

**Comment by pirelenito** [comment]
We could memoize the `materialize` as well. Good point!

**Comment by pirelenito** [comment]
We are going to favor a different implementation. See #6.
